## provide the name of the namespace
namespace:
  name: production

replicaCount: 5

image:
  imagePullPolicy : Always

resources:
  limits:
    memory: "256Mi"
    cpu: "500m"
  requests:
    memory: "128Mi"
    cpu: "350m"

service:
  port: 7111
